image: node
# variables:
#   GIT_STRATEGY: clone
stages: # Stages 表示构建阶段
  - check
  - changelog

cache: &global_cache
  key: $CI_COMMIT_REF_SLUG
  paths:
    - node_modules

default:
  before_script:
    - echo "====== 管理器版本 ======"
    - node -v
    - npm -v
    - pnpm -v
    - echo "====== 变更版本 ======"
    - nvm use v16.18.1

check-staging:
  stage: check
  cache:
    # 继承全局配置
    <<: *global_cache
    # 覆盖 policy
    policy: push
  only:
    refs:
      - alpha
      - beta
      - RC
      - master
    changes:
      - package.json
      - pnpm-lock.yaml
      - \.gitlab-ci.yml
  tags:
    - bill
  script:
    - echo "===== 依赖发生变化, 重新安装依赖 ======"
    # - npm config set sass_binary_site https://registry.npmmirror.com/binary.html?path=node-sass
    # - npm config set sass_binary_site https://npm.taobao.org/mirrors/node-sass/
    - pnpm install --registry=http://192.168.10.81:8888 # 安装依赖
    - echo "===== 依赖重新安装完成 ======"

# CHANGELOG
changelog:deploy:
  stage: changelog
  cache:
    # 继承全局配置
    <<: *global_cache
    # 覆盖 policy
    policy: pull
  tags:
    - bill
  only:
    refs:
      - alpha
      - beta
      - RC
      - master
  script:
    - echo "===== generate changelog start ======"
    - pnpm run semantic-release
    - echo "=====  generate changelog end ======"
